In [1]:
import numpy as np

In [2]:
np.array([10, 20, 24, 5, 15, 50])        #Es como una serie de pandas o una lista (no son filas, ni columnas)

array([10, 20, 24,  5, 15, 50])

In [3]:
a = np.array([10, 30, 20, 4, 30, 51, 7, 2, 4, 40, 100])
a[4]

30

In [4]:
a[3:]

array([  4,  30,  51,   7,   2,   4,  40, 100])

In [5]:
a[3:7]

array([ 4, 30, 51,  7])

In [6]:
a[1::4]

array([30, 51, 40])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
ones = np.ones((4, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
type(ones)

numpy.ndarray

In [12]:
type(ones[3])

numpy.ndarray

In [13]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [14]:
b = np.array( [['x', 'y', 'z'], ['a', 'c', 'e']])      #Exactamente como un dataframe de pandas (filas (x,y,z)y columnas(x,a)) 
print(b)
type(b)

[[&#39;x&#39; &#39;y&#39; &#39;z&#39;]
 [&#39;a&#39; &#39;c&#39; &#39;e&#39;]]


numpy.ndarray

In [15]:
b.ndim

2

In [16]:
c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [17]:
cabeceras = [ ('nombre', 'S10' ), ('edad', int) ]
datos = [ ('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15) ]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad' )


array([(b&#39;Juan&#39;, 10), (b&#39;Samuel&#39;, 15), (b&#39;Javier&#39;, 42), (b&#39;Maria&#39;, 70)],
      dtype=[(&#39;nombre&#39;, &#39;S10&#39;), (&#39;edad&#39;, &#39;&lt;i4&#39;)])

In [18]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
np.full( ( 3, 5 ), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [22]:
np.diag ( [0, 3, 9, 10] )

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

## Random Enteros 

In [23]:
np.random.randint(100)

25

In [31]:
np.random.randint(1,100,10)    #Dos primeros numeros num aleatorios, el tercero el rango 

array([54,  6, 32, 43, 86, 18,  3, 27,  9, 53])

In [24]:
np.random.randint(100, size=(5))

array([21, 49, 68, 72, 39])

In [25]:
np.random.randint(100, size=(3, 5))

array([[ 3, 69, 58, 25, 26],
       [33,  9, 65, 99, 44],
       [93, 28, 35, 87, 84]])

## Random Floats

In [26]:
np.random.rand()    #random = rand

0.5328435047902437

In [27]:
np.random.rand(5)

array([0.72712045, 0.1008667 , 0.4675457 , 0.20901186, 0.41714802])

In [28]:
np.random.rand(3, 5)

array([[0.44673503, 0.44746424, 0.82098055, 0.2874032 , 0.43279008],
       [0.02775599, 0.11751806, 0.12457382, 0.48128661, 0.91817697],
       [0.16424881, 0.92437796, 0.92788083, 0.98568827, 0.75893974]])

## Choice

In [29]:
np.random.choice([3, 5, 7, 9])

3

In [30]:
np.random.choice([3, 5, 7, 9], size=(3, 5))

array([[3, 9, 9, 5, 7],
       [3, 3, 7, 5, 7],
       [3, 5, 9, 5, 9]])