In [1]:
import numpy as np
import pandas as pd

In [2]:
lista = [10,20,30,40,50,60]
lista

[10, 20, 30, 40, 50, 60]

In [2]:
np.nan       

nan

In [3]:
a = np.array(lista)
a

array([10, 20, 30, 40, 50, 60])

In [4]:
a.ndim  #Dimensiones

1

In [5]:
a.size  #Tamaño del array

6

In [6]:
a.shape  #Elementos en cada dimension

(6,)

In [7]:
a[0]  #Obtener objetos del array a traves de indices

10

In [47]:
a[0:5]     #Slides con nnumpy  a[::-1]  

array([10, 20, 30, 40, 50])

In [16]:
a[[0,0,3,4]]    #Encontrar valores

array([10, 10, 40, 50])

In [17]:
a * 10

array([100, 200, 300, 400, 500, 600])

In [19]:
np.array([1,1.2,1.3,1.6,2,3,4],dtype= 'i')    #Para convertir todos los objetos en floats o integers  i o f (float32)

array([1, 1, 1, 1, 2, 3, 4], dtype=int32)

In [23]:
np.arange(0,10)      #Rango con array   (0,10,2) ultimo numero da saltos

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#np.zeros(10) #ones(5)
#np.full(10,5)
#np.random.random(10)
#np.linspace(0,10,10)
np.random.randint(0,25,10)     #Numeros Aleatorios

array([ 7, 23,  5, 15,  1,  6, 11,  3, 12,  1])

In [33]:
b = np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]])
b

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [42]:
#b[0,1] 
b[1,1:4]

array([20, 30, 40])

In [48]:
b.ravel()   #Una vista
#b.flatten() #Una copia

array([  1,   2,   3,   4,   5,  10,  20,  30,  40,  50, 100, 200, 300,
       400, 500])

In [91]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
#a[5] = 100
#a[0:4] = 20
#a[[4,6,7]] =10
#a = np.append(a,50)  #Pueden ser dos numeros  [50,50]
a = np.delete(a,5)  #Borra el elemento indice
a

array([20, 20, 20, 20, 10, 10, 10,  8,  9, 50])

In [97]:
c = np.arange(0,15)   #array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]) Partir un array en dimensiones
c.shape = (3,5)       #3 Filas y 5 Columnas 
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [98]:
c.shape= (c.size,)    #Volverlo a unir
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [99]:
a = np.arange(0,10).reshape(2,5)   
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [100]:
a.T     #Transposición

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [101]:
b = np.arange(1,11)   #Operaciones Básicas
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
a = b * 2   #+10, /2, (a*10/2) etc
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
a.sum()    #min(), max()

110

In [104]:
a.std()   #Desviación estandar

5.744562646538029

In [105]:
a.mean()   #Media o Promedio 

11.0

In [61]:
a = np.arange(0,10).reshape(2,5)
b = np.arange(0,10).reshape(2,5)
a,b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [62]:
a * b      #Multiplicaciones entre dimensiones

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [106]:
a = np.random.randint(1,100,25)        #Ordenamiento, con la func randint de np se puede sacar el rango de numeros
a.sort()    #Ascendente
a

array([19, 19, 20, 21, 21, 23, 27, 31, 34, 35, 37, 39, 39, 40, 42, 43, 50,
       53, 67, 72, 79, 87, 92, 94, 96])

In [107]:
a[::-1]  #Descendente

array([96, 94, 92, 87, 79, 72, 67, 53, 50, 43, 42, 40, 39, 39, 37, 35, 34,
       31, 27, 23, 21, 21, 20, 19, 19])

In [65]:
def operacion_simple(valor):        #Ejecución funciones
    return valor * 10

a = np.random.randint(1,100,10)     
a.sort()
print(a)
for i in a:
    print(operacion_simple(i))

[18 18 20 30 36 46 56 70 73 93]
180
180
200
300
360
460
560
700
730
930


In [108]:
#Operadores Lógicos
a = np.random.randint(1,100,10)
a

array([63, 59,  9, 42, 46, 70, 40, 88, 71, 87])

In [109]:
a[a > 60]

array([63, 70, 88, 71, 87])

In [110]:
#Lectura de Archivos
a = np.random.randint(1,100,10)
a

array([96, 82, 15, 11, 55, 59,  9, 78, 37, 88])

In [69]:
np.savetxt('./Numpy/ejemplo.csv',a) #,delimiter= ';')  Puede ser txt o csv o npz(binario)

In [70]:
a = np.loadtxt('./Numpy/ejemplo.txt')
b = np.array(a,dtype = 'i')
b

array([68,  9, 49, 12,  4, 16, 14, 30, 87, 33], dtype=int32)

In [71]:
np.savez('./Numpy/ejemplo.npz',a)

In [72]:
np.load('./Numpy/ejemplo.npz')

In [73]:
np.load('./Numpy/ejemplo.npz')['arr_0']         #Para cargarlo

array([68.,  9., 49., 12.,  4., 16., 14., 30., 87., 33.])

In [ ]:
#Jalar de un archivo de texto 
np.genfromtxt('nombre del archivo', usecols=[1,2], skip_header=1,comments='#',delimiter',')

In [111]:
train_df = pd.read_csv('titanic-train.csv')
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [117]:
a = np.where(train_df['Pclass'] == 3,'C',train_df['Pclass'])
train_df['Pclass1'] = a
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked Pclass1  
0      0         A/5 21171   7.2500   NaN        S       C  
1      0          PC 17599  71.2833   C85        C       1  
2      0  STON/O2. 3101282   7.9250   NaN        S       C  
3      0            113803  53.1000  C123        S       1  
4      0            373450   8.0500   NaN        S       C

In [129]:
Pclass2 = []
for i in train_df['Pclass']:    
    if i == 1:
        Pclass2.append('A')
    elif i ==2:
        Pclass2.append('B')
    else:
        Pclass2.append('C')
        
Pclass2
train_df['Pclass2'] = Pclass2    
train_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked Pclass2  
0        0         A/5 21171   7.2500   NaN        S       C  
1        0          PC 17599  71.2833   C85        C       A  
2        0  STON/O2. 3101282   7.9250   NaN        S       C  
3        0            113803  53.1000  C123        S       A  
4        0            373450   8.0500   NaN        S       C  
..     ...               ...      ...   ...      ...     ...  
886      0            211536  13.0000   NaN        S       B  
887      0            112053  30.0000   B42        S       A  
888      2        W./C. 6607  23.4500   NaN        S       C  
889      0            111369  30.0000  C148        C       A  
890      0            370376   7.7500   NaN        Q       C  

[891 rows x 13 columns]

In [ ]:
categorias = train_df['Pclass2'].value_counts().index
print(categorias)